image: node

build:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build-ci
    - rm -rf public
    - cp build/index.html build/404.html
  artifacts:
    paths:
      - build

pages:
  stage: deploy
  dependencies: 
    - build
  artifacts:
    paths:
      - public
  script:
    - rm -rf build
    - mv build public
  only:
    - master
